base: --no-source --color --format pretty -p html_report
html_report: --format progress --format html --out=reports/features_report.html
default: --profile qa

local: --profile base PROFILE=local
qa: --profile base PROFILE=qa
prod: --profile base PROFILE=prod